version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: flux-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: flux
      POSTGRES_USER: flux_user
      POSTGRES_PASSWORD: flux_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flux-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flux_user -d flux"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: flux-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: flux_user
      MONGO_INITDB_ROOT_PASSWORD: flux_password
      MONGO_INITDB_DATABASE: flux
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - flux-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: flux-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass flux_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - flux-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flux-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # PostgreSQL
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: flux_db
      POSTGRES_USER: flux_user
      POSTGRES_PASSWORD: flux_password
      # MongoDB
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DB: flux_db
      MONGODB_USER: flux_user
      MONGODB_PASSWORD: flux_password
      MONGODB_URI: mongodb://flux_user:flux_password@mongodb:27017/flux_db?authSource=admin
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: flux_password
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - flux-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  flux-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local
