version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: flux-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: flux_db_dev
      POSTGRES_USER: flux_user
      POSTGRES_PASSWORD: flux_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flux-network-dev

  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: flux-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: flux_user
      MONGO_INITDB_ROOT_PASSWORD: flux_password
      MONGO_INITDB_DATABASE: flux_db_dev
    volumes:
      - mongodb_dev_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - flux-network-dev

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: flux-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass flux_password
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - flux-network-dev

networks:
  flux-network-dev:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
  mongodb_dev_data:
    driver: local
  redis_dev_data:
    driver: local
