version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine3.22
    container_name: flux-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: flux
      POSTGRES_USER: flux_user
      POSTGRES_PASSWORD: flux_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flux-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flux_user -d flux"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: flux-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: flux_user
      MONGO_INITDB_ROOT_PASSWORD: flux_password
      MONGO_INITDB_DATABASE: flux
    volumes:
      - mongodb_data:/data/db
    networks:
      - flux-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: flux-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass flux_password
    volumes:
      - redis_data:/data
    networks:
      - flux-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flux-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      NODE_ENV: production
      CONFIG_NAME: docker.config.env
      WEB_PATH: ../web/dist
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - flux-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  flux-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
